[project]
name = "fido2-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fido2==1.0.0",
    "keyring>=25.6.0",
    "pytest>=8.4.1",
    "pyobjc; sys_platform == 'darwin'",
    "winsdk; sys_platform == 'win32'"
]
